[package]
name = "neural-networks"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
thiserror = "2.0.3"
memory = { path = "../../memory/rust" }
linear-algebra = { path = "../../linear-algebra/rust" }